project_id: 911151
preserve_hierarchy: true

files:
  - source: "/app/src/main/res/values/strings.xml"
    translation: "/app/src/main/res/values-%android_code%/%original_file_name%"
    skip_untranslated_strings: true
    languages_mapping:
      android_code:
        # Spanish
        es-ES: es

        # Indonesian
        id: in

        # Chinese
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        zh-HK: zh-rHK

        # Urdu
        ur-PK: ur
        ur-IN: ur-rIN

        # Portuguese
        pt-BR: pt-rBR
        pt-PT: pt-rPT

        # Other languages
        cs: cs
        de: de
        et: et
        fa: fa
        fi: fi
        fr: fr
        hu: hu
        it: it
        ja: ja
        ka: ka
        ko: ko
        nl: nl
        pl: pl
        ru: ru
        sk: sk
        ta: ta
        tr: tr
        uk: uk
        vi: vi
        eu: eu

    excluded_target_languages:
      - en
      - en-US

  - source: "/fastlane/metadata/android/en-US/title.txt"
    translation: "/fastlane/metadata/android/%locale%/%original_file_name%"
    languages_mapping:
      locale:
        fr: fr-FR
        es-ES: es-ES
        cs: cs-CZ
        de: de-DE
        eu: eu
        fi: fi-FI
        hu: hu-HU
        it: it-IT
        ja: ja-JP
        ka: ka-GE
        ko: ko-KR
        nl: nl-NL
        pl: pl-PL
        pt-PT: pt-PT
        ru: ru-RU
        sk: sk
        tr: tr-TR
        uk: uk
        zh-CN: zh-CN
        zh-TW: zh-TW
        ur-PK: ur-PK
        vi: vi
        pt-BR: pt-BR
        id: id
        fa: fa-IR
        ta: ta-IN
        et: et
    excluded_target_languages:
      - en
      - en-US

  - source: "/fastlane/metadata/android/en-US/short_description.txt"
    translation: "/fastlane/metadata/android/%locale%/%original_file_name%"
    skip_untranslated_files: true
    languages_mapping:
      locale:
        fr: fr-FR
        es-ES: es-ES
        cs: cs-CZ
        de: de-DE
        eu: eu
        fi: fi-FI
        hu: hu-HU
        it: it-IT
        ja: ja-JP
        ka: ka-GE
        ko: ko-KR
        nl: nl-NL
        pl: pl-PL
        pt-PT: pt-PT
        ru: ru-RU
        sk: sk
        tr: tr-TR
        uk: uk
        zh-CN: zh-CN
        zh-TW: zh-TW
        ur-PK: ur-PK
        vi: vi
        pt-BR: pt-BR
        id: id
        fa: fa-IR
        ta: ta-IN
        et: et
    excluded_target_languages:
      - en
      - en-US

  - source: "/fastlane/metadata/android/en-US/full_description.txt"
    translation: "/fastlane/metadata/android/%locale%/%original_file_name%"
    skip_untranslated_files: true
    languages_mapping:
      locale:
        fr: fr-FR
        es-ES: es-ES
        cs: cs-CZ
        de: de-DE
        eu: eu
        fi: fi-FI
        hu: hu-HU
        it: it-IT
        ja: ja-JP
        ka: ka-GE
        ko: ko-KR
        nl: nl-NL
        pl: pl-PL
        pt-PT: pt-PT
        ru: ru-RU
        sk: sk
        tr: tr-TR
        uk: uk
        zh-CN: zh-CN
        zh-TW: zh-TW
        ur-PK: ur-PK
        vi: vi
        pt-BR: pt-BR
        id: id
        fa: fa-IR
        ta: ta-IN
        et: et
    excluded_target_languages:
      - en
      - en-US

commit_message: "chore: update translations from Crowdin"
append_commit_message: false